[tox]
envlist =
    py{36, 37, 38, 39}-dj{111}
    py{36, 37, 38, 39, 310}-dj{22}
    py{36, 37, 38, 39, 310, 311}-dj{32}
    py{38, 39, 310, 311}-dj{42}
    flake8
    bandit
    coverage

[testenv]
usedevelop = True
deps =
    dj111: Django>=1.11,<2.0
    dj22: Django>=2.2,<3.0
    dj32: Django>=3.2,<4.0
    dj42: Django>=4.2,<5.0

    teamcity-messages==1.21
    coverage==4.5.1

    ; Install the requirements for the test environment
    .[test]

changedir = patchman_django_sharding
passenv = DATABASE_URL DATABASE_URL2
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.teamcity
    py36: VIRTUALENV_PIP = 21.3.1
commands =
    ; Django 1.8 doesn't have parallel tests and Django 1.9 and Django 1.10 don't support sub tests with parallel
    ; testing: https://code.djangoproject.com/ticket/26942. Since we do want to speedup tests, we don't use subTests in
    ; our code base, so we can run tests in parallel for Django 1.9+
    dj18: coverage run manage.py test --noinput {posargs}
    !dj18: coverage run manage.py test --noinput --parallel {posargs}

[testenv:flake8]
deps =
    flake8==3.5.0
    flake8-teamcity==0.0.4
changedir = {toxinidir}
ignore_errors = true
setenv =
    VIRTUALENV_PIP = 21.3.1
commands =
    ; Beginning the line with a `-` will ignore the exit code. This is what we want, because we don't want the linters
    ; to fail the tests.
    - flake8 --format=teamcity patchman_django_sharding

[testenv:bandit]
deps =
    bandit==1.4.1.dev7
changedir = {toxinidir}
ignore_errors = true
setenv =
    VIRTUALENV_PIP = 21.3.1
commands =
    ; Beginning the line with a `-` will ignore the exit code. This is what we want, because we don't want the linters
    ; to fail the tests.
    - bandit -r patchman_django_sharding/ --ini {toxinidir}/.bandit -f teamcity

[testenv:coverage]
deps =
    coverage==4.5.1
setenv =
    VIRTUALENV_PIP = 21.3.1
commands =
    coverage html
    python {toxinidir}/coverage.py
