[tox]
envlist =
    py314-dj60
    flake8
    bandit
    coverage

[testenv]
usedevelop = True
deps =
    Django>=6.0,<7.0
    psycopg[binary]>=3.0.0
    setuptools>=68

    ; Install the requirements for the test environment
    .[test]

changedir = djanquiltdb
passenv =
    DATABASE_URL
    DATABASE_URL2
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.dev
    VIRTUALENV_PIP = 23.3.1
commands =
    coverage run manage.py test --noinput {posargs} --parallel

[testenv:flake8]
deps =
    flake8==3.5.0
changedir = {toxinidir}
ignore_errors = true
commands =
    ; Beginning the line with a `-` will ignore the exit code. This is what we want, because we don't want the linters
    ; to fail the tests.
    - flake8 djanquiltdb

[testenv:bandit]
deps =
    bandit==1.6.2
changedir = {toxinidir}
ignore_errors = true
commands =
    ; Beginning the line with a `-` will ignore the exit code. This is what we want, because we don't want the linters
    ; to fail the tests.
    - bandit -r djanquiltdb/ --ini {toxinidir}/.bandit

[testenv:coverage]
commands =
    - coverage html
    python {toxinidir}/coverage.py
