[tox]
envlist = py{34,36}

[testenv]
usedevelop = True
deps =
    -r{toxinidir}/requirements/teamcity.txt
changedir = django_sharding
passenv = DATABASE_URL DATABASE_URL2
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.teamcity
commands =
    coverage run --branch manage.py test --noinput {posargs}
