# Generated by Django 6.0.8 on 2026-08-26 13:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ShardedProtected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PublicProtected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='publicprotected',
            trigger=pgtrigger.compiler.Trigger(
                name='protect_deletes',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash='17fe4bfd171b2f3a8bb4ee95b898bee3a77faf5c',
                    operation='DELETE',
                    pgid='pgtrigger_protect_deletes_7a5cd',
                    table='pgtrigger_tests_publicprotected',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shardedprotected',
            trigger=pgtrigger.compiler.Trigger(
                name='protect_deletes',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash='30f940a0bec40d69ca183aff05e4d9e71821aed8',
                    operation='DELETE',
                    pgid='pgtrigger_protect_deletes_52cf6',
                    table='pgtrigger_tests_shardedprotected',
                    when='BEFORE',
                ),
            ),
        ),
    ]
