from io import StringIO
from unittest import mock

from django.core.management import CommandError, call_command
from django.db import DatabaseError

from djanquiltdb import State
from djanquiltdb.db import connection
from djanquiltdb.postgresql_backend.base import PUBLIC_SCHEMA_NAME, DatabaseWrapper
from djanquiltdb.utils import create_template_schema, use_shard
from djanquiltdb_tests import ShardingTransactionTestCase
from example.models import Shard


class AlignShardsWithTemplateTestCase(ShardingTransactionTestCase):
    """
    The template has:
    - widget, renamed from legacy_widget, with a serial primary key that takes its values from legacy_widget_code_seq;
    - gadget, renamed from legacy_gadget, with an identity primary key whose constraint is named legacy_gadget_pkey and
      whose sequence is named legacy_gadget_code_seq;
    - ticket_number, a sequence with non-default settings, and scratch_number, an unlogged sequence.
    """

    def setUp(self):
        super().setUp()
        create_template_schema('default')
        cursor = connection.cursor()
        cursor.execute('CREATE TABLE template.legacy_widget (code SERIAL PRIMARY KEY)')
        cursor.execute('ALTER TABLE template.legacy_widget RENAME TO widget')
        cursor.execute('CREATE TABLE template.legacy_gadget (code BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)')
        cursor.execute('ALTER TABLE template.legacy_gadget RENAME TO gadget')
        cursor.execute(
            'CREATE SEQUENCE template.ticket_number AS integer'
            ' START WITH 50 INCREMENT BY 10 MINVALUE 5 MAXVALUE 100000 CACHE 3 CYCLE'
        )
        cursor.execute('CREATE UNLOGGED SEQUENCE template.scratch_number')

        self.shard = Shard.objects.create(
            alias='sinaloa', schema_name='el_chapo', node_name='default', state=State.ACTIVE
        )
        self.other_shard = Shard.objects.create(
            alias='medellin', schema_name='pablo_escobar', node_name='default', state=State.ACTIVE
        )

    @staticmethod
    def _make_shard_differ_from_template(schema_name):
        """
        Make the shard differ from the template in every way the command fixes: widget.code does not own its sequence,
        ticket_number has the default settings, scratch_number is logged, and gadget's primary key and identity
        sequence are named after the table.
        """
        cursor = connection.cursor()
        cursor.execute('ALTER SEQUENCE {}.legacy_widget_code_seq OWNED BY NONE'.format(schema_name))
        cursor.execute(
            'ALTER SEQUENCE {}.ticket_number AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807'
            ' START WITH 1 CACHE 1 NO CYCLE'.format(schema_name)
        )
        cursor.execute('ALTER SEQUENCE {}.scratch_number SET LOGGED'.format(schema_name))
        cursor.execute('ALTER TABLE {}.gadget RENAME CONSTRAINT legacy_gadget_pkey TO gadget_pkey'.format(schema_name))
        cursor.execute('ALTER SEQUENCE {}.legacy_gadget_code_seq RENAME TO gadget_code_seq'.format(schema_name))

    @staticmethod
    def _aligned_properties(schema_name):
        """Return the properties that the command aligns, in a form that can be compared with the template's."""
        cursor = connection.cursor()
        cursor.execute('SELECT pg_get_serial_sequence(%s, %s)', ['{}.widget'.format(schema_name), 'code'])
        widget_sequence = cursor.fetchone()[0]
        cursor.execute('SELECT pg_get_serial_sequence(%s, %s)', ['{}.gadget'.format(schema_name), 'code'])
        gadget_sequence = cursor.fetchone()[0]
        cursor.execute(
            """
            SELECT con.conname::text FROM pg_catalog.pg_constraint con
              JOIN pg_catalog.pg_class cls ON cls.oid = con.conrelid
              JOIN pg_catalog.pg_namespace nsp ON nsp.oid = cls.relnamespace
              WHERE nsp.nspname = %s AND cls.relname = 'gadget' AND con.contype = 'p'
            """,
            [schema_name],
        )
        gadget_primary_key = cursor.fetchone()[0]
        cursor.execute(
            'SELECT seqtypid::regtype::text, seqstart, seqincrement, seqmin, seqmax, seqcache, seqcycle'
            ' FROM pg_catalog.pg_sequence WHERE seqrelid = %s::regclass',
            ['{}.ticket_number'.format(schema_name)],
        )
        ticket_number_settings = cursor.fetchone()
        cursor.execute(
            'SELECT relpersistence FROM pg_catalog.pg_class WHERE oid = %s::regclass',
            ['{}.scratch_number'.format(schema_name)],
        )
        scratch_number_persistence = cursor.fetchone()[0]
        return {
            'widget_sequence': widget_sequence and widget_sequence.split('.')[1],
            'gadget_sequence': gadget_sequence.split('.')[1],
            'gadget_primary_key': gadget_primary_key,
            'ticket_number_settings': ticket_number_settings,
            'scratch_number_persistence': scratch_number_persistence,
        }

    def call_command(self, **options):
        stdout = StringIO()
        call_command('align_shards_with_template', stdout=stdout, **options)
        return stdout.getvalue()

    def test_aligns_a_shard_that_differs_from_the_template(self):
        """
        Case: A shard differs from the template: its serial sequence is not owned by its column, a sequence has the
              default settings, an unlogged sequence is logged, and its primary key and identity sequence are named
              after the table.
        Expected: After the command, the shard matches the template in each of these.
        """
        self._make_shard_differ_from_template('el_chapo')
        self.assertNotEqual(self._aligned_properties('el_chapo'), self._aligned_properties('template'))

        self.call_command()

        self.assertEqual(self._aligned_properties('el_chapo'), self._aligned_properties('template'))

    def test_keeps_the_positions_of_the_shards_sequences(self):
        """
        Case: The shard's serial, identity and standalone sequences were advanced, and then the shard was made to
              differ from the template.
        Expected: After the command, every sequence continues from its position on the shard.
        """
        cursor = connection.cursor()
        cursor.execute('INSERT INTO el_chapo.widget SELECT FROM generate_series(1, 2)')
        cursor.execute('INSERT INTO el_chapo.gadget SELECT FROM generate_series(1, 3)')
        cursor.execute("SELECT nextval('el_chapo.ticket_number')")
        self._make_shard_differ_from_template('el_chapo')
        cursor.execute('SELECT last_value, is_called FROM el_chapo.ticket_number')
        ticket_number_position = cursor.fetchone()

        self.call_command()

        cursor.execute('INSERT INTO el_chapo.widget DEFAULT VALUES RETURNING code')
        self.assertEqual(cursor.fetchone()[0], 3)
        cursor.execute('INSERT INTO el_chapo.gadget DEFAULT VALUES RETURNING code')
        self.assertEqual(cursor.fetchone()[0], 4)
        cursor.execute('SELECT last_value, is_called FROM el_chapo.ticket_number')
        self.assertEqual(cursor.fetchone(), ticket_number_position)

    def test_prints_the_statements_it_runs(self):
        """
        Case: One shard differs from the template, and the other matches it.
        Expected: The output lists the statements run on the shard that differs, and says that the other shard matches
                  the template.
        """
        self._make_shard_differ_from_template('el_chapo')

        output = self.call_command()

        self.assertIn('Aligning default|el_chapo with the template:\n', output)
        self.assertIn('    ALTER SEQUENCE el_chapo.legacy_widget_code_seq OWNED BY el_chapo.widget.code;\n', output)
        self.assertIn('    ALTER SEQUENCE el_chapo.scratch_number SET UNLOGGED;\n', output)
        self.assertIn('default|pablo_escobar matches the template.\n', output)

    def test_dry_run_changes_nothing(self):
        """
        Case: A shard differs from the template, and the command runs with --dry-run.
        Expected: The output lists the statements, and the shard is unchanged.
        """
        self._make_shard_differ_from_template('el_chapo')
        properties_before = self._aligned_properties('el_chapo')

        output = self.call_command(dry_run=True)

        self.assertIn('Aligning default|el_chapo with the template:\n', output)
        self.assertIn('Dry run: nothing was changed.\n', output)
        self.assertEqual(self._aligned_properties('el_chapo'), properties_before)

    def test_dry_run_leaves_the_clone_functions_unchanged(self):
        """
        Case: public.template_alignment_statements was dropped, and the command runs with --dry-run.
        Expected: The function is still missing afterwards.
        """
        cursor = connection.cursor()
        cursor.execute('DROP FUNCTION public.template_alignment_statements(text, text, boolean)')
        self.addCleanup(connection.set_clone_function)

        self.call_command(dry_run=True)

        cursor.execute("SELECT to_regprocedure('public.template_alignment_statements(text, text, boolean)')")
        self.assertIsNone(cursor.fetchone()[0])

    @mock.patch('djanquiltdb.postgresql_backend.base.DatabaseWrapper.acquire_advisory_lock')
    def test_takes_the_lock_of_each_shard(self, mock_acquire_lock):
        """
        Case: The command runs over both shards, and one of them is in maintenance.
        Expected: A shared, transaction-scoped advisory lock is taken on each shard. A shard move takes the same lock
                  exclusively.
        """
        Shard.objects.filter(id=self.other_shard.id).update(state=State.MAINTENANCE)
        # The flush on teardown refuses a shard in maintenance.
        self.addCleanup(Shard.objects.filter(id=self.other_shard.id).update, state=State.ACTIVE)

        self.call_command()

        for shard in (self.shard, self.other_shard):
            with self.subTest(shard=shard.schema_name):
                mock_acquire_lock.assert_any_call('shard_{}'.format(shard.id), shared=True, xact=True)

    def test_a_shard_without_a_schema(self):
        """
        Case: Both shards differ from the template, and the schema of one of them was dropped.
        Expected: A CommandError that names the shard without a schema, raised before the other shard is aligned.
        """
        self._make_shard_differ_from_template('el_chapo')
        properties_before = self._aligned_properties('el_chapo')
        cursor = connection.cursor()
        cursor.execute('DROP SCHEMA pablo_escobar CASCADE')
        self.addCleanup(cursor.execute, 'CREATE SCHEMA pablo_escobar')  # Deleting the shard on teardown drops it.

        with self.assertRaisesMessage(CommandError, 'default|pablo_escobar'):
            self.call_command()

        self.assertEqual(self._aligned_properties('el_chapo'), properties_before)

    def test_a_node_without_a_template(self):
        """
        Case: The default node's shard differs from the template, and the other node has a shard but no template.
        Expected: A CommandError that names the other node, raised before the default node's shard is aligned.
        """
        create_template_schema('other')
        Shard.objects.create(alias='cali', schema_name='gilberto', node_name='other', state=State.ACTIVE)
        with use_shard(node_name='other', schema_name=PUBLIC_SCHEMA_NAME) as env:
            env.connection.cursor().execute('DROP SCHEMA template CASCADE')
        self._make_shard_differ_from_template('el_chapo')
        properties_before = self._aligned_properties('el_chapo')

        with self.assertRaisesMessage(CommandError, "'other'"):
            self.call_command()

        self.assertEqual(self._aligned_properties('el_chapo'), properties_before)

    def test_a_second_run_finds_nothing_to_align(self):
        """
        Case: The command aligned a shard that differed from the template, and then runs again.
        Expected: The second run reports that every shard matches the template.
        """
        self._make_shard_differ_from_template('el_chapo')
        self.call_command()

        output = self.call_command()

        self.assertEqual(
            output,
            'default|el_chapo matches the template.\ndefault|pablo_escobar matches the template.\n'
            "Node 'other' has no shards.\n",
        )

    def test_schema_name_limits_the_command_to_that_shard(self):
        """
        Case: Both shards differ from the template, and the command runs with --schema-name for one of them.
        Expected: Only that shard is aligned.
        """
        self._make_shard_differ_from_template('el_chapo')
        self._make_shard_differ_from_template('pablo_escobar')
        other_properties_before = self._aligned_properties('pablo_escobar')

        self.call_command(schema_name='el_chapo')

        self.assertEqual(self._aligned_properties('el_chapo'), self._aligned_properties('template'))
        self.assertEqual(self._aligned_properties('pablo_escobar'), other_properties_before)

    def test_schema_name_of_an_unknown_shard(self):
        """
        Case: The command runs with a --schema-name that no shard has.
        Expected: A CommandError that names the schema.
        """
        with self.assertRaisesMessage(CommandError, "No shard has the schema name 'nobody'."):
            self.call_command(schema_name='nobody')

    def test_a_node_without_shards(self):
        """
        Case: The command runs for the other node, which has no shards.
        Expected: The output says that the node has no shards.
        """
        self.assertEqual(self.call_command(database='other'), "Node 'other' has no shards.\n")

    def test_installs_the_clone_functions_once_per_node(self):
        """
        Case: The command runs over the two shards of the default node.
        Expected: The functions that list the statements are installed once, not once per shard.
        """
        with mock.patch(
            'djanquiltdb.postgresql_backend.base.DatabaseWrapper.set_clone_function',
            autospec=True,
            side_effect=DatabaseWrapper.set_clone_function,
        ) as mock_set_clone_function:
            self.call_command()

        self.assertEqual(mock_set_clone_function.call_count, 1)

    @mock.patch(
        'djanquiltdb.postgresql_backend.base.DatabaseWrapper.set_clone_function',
        side_effect=DatabaseError('permission denied for schema public'),
    )
    def test_a_failure_installing_the_clone_functions(self, mock_set_clone_function):
        """
        Case: Installing the functions that list the statements fails.
        Expected: A CommandError that names the error and the shards that were not aligned.
        """
        with self.assertRaisesMessage(
            CommandError,
            'default|el_chapo cannot be aligned with the template: permission denied for schema public Shards not'
            ' aligned: default|el_chapo, default|pablo_escobar.',
        ):
            self.call_command()

    @mock.patch(
        'djanquiltdb.management.commands.align_shards_with_template.Command.apply_alignment_to_shard',
        side_effect=DatabaseError(),
    )
    def test_a_failure_without_a_message(self, mock_apply_alignment_to_shard):
        """
        Case: Aligning a shard fails with a database error that has no message.
        Expected: A CommandError that names the type of error and the shards that were not aligned.
        """
        with self.assertRaisesMessage(
            CommandError,
            'default|el_chapo cannot be aligned with the template: DatabaseError Shards not aligned: default|el_chapo,'
            ' default|pablo_escobar.',
        ):
            self.call_command()

    def test_aligns_the_shards_of_a_node_in_schema_name_order(self):
        """
        Case: A third shard is created after the other two, with a schema name that sorts before theirs.
        Expected: The output lists the shards in the order of their schema names.
        """
        Shard.objects.create(alias='guadalajara', schema_name='amado', node_name='default', state=State.ACTIVE)

        output = self.call_command()

        self.assertEqual(
            output,
            'default|amado matches the template.\n'
            'default|el_chapo matches the template.\n'
            'default|pablo_escobar matches the template.\n'
            "Node 'other' has no shards.\n",
        )

    @staticmethod
    def _create_gizmo_with_its_identity_sequence_name_in_use(schema_name):
        """
        Create a sequence gizmo_id_seq that no column owns, and then a table gizmo with an identity column. Because
        gizmo_id_seq is already in use, PostgreSQL names gizmo's identity sequence gizmo_id_seq1. A shard gets into this
        state when a dropped table leaves its sequence behind, and a newer table with the same name gets an identity
        column.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE SEQUENCE {}.gizmo_id_seq'.format(schema_name))
        cursor.execute(
            'CREATE TABLE {}.gizmo (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)'.format(schema_name)
        )

    def _set_up_an_identity_sequence_name_clash(self):
        """
        Give the template a table gizmo with an identity column, whose identity sequence is named gizmo_id_seq. On
        el_chapo, a sequence that no column owns has that name, so el_chapo's gizmo has the identity sequence
        gizmo_id_seq1. pablo_escobar gets a plain copy of gizmo. Both shards are also made to differ from the template
        with _make_shard_differ_from_template.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE TABLE template.gizmo (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)')
        self._create_gizmo_with_its_identity_sequence_name_in_use('el_chapo')
        cursor.execute('CREATE TABLE pablo_escobar.gizmo (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)')
        self._make_shard_differ_from_template('el_chapo')
        self._make_shard_differ_from_template('pablo_escobar')

    def test_rename_to_a_name_already_used_by_another_relation(self):
        """
        Case: The template's gizmo has the identity sequence gizmo_id_seq. On el_chapo, a sequence that no column owns
              has that name, so el_chapo's gizmo has the identity sequence gizmo_id_seq1.
        Expected: A CommandError that names the shard, the name already in use and the shards that were not aligned,
                  and el_chapo is unchanged.
        """
        self._set_up_an_identity_sequence_name_clash()
        properties_before = self._aligned_properties('el_chapo')

        with self.assertRaisesMessage(
            CommandError,
            'default|el_chapo cannot be aligned with the template: Schema el_chapo cannot be aligned with schema template:'
            ' el_chapo.gizmo_id_seq already exists, so gizmo_id_seq1 cannot be renamed to it Shards not aligned:'
            ' default|el_chapo, default|pablo_escobar.',
        ):
            self.call_command()

        self.assertEqual(self._aligned_properties('el_chapo'), properties_before)

    def test_skip_name_clashes_skips_a_rename_to_a_name_already_used_by_another_relation(self):
        """
        Case: The template's gizmo has the identity sequence gizmo_id_seq. On el_chapo, a sequence that no column owns
              has that name, so el_chapo's gizmo has the identity sequence gizmo_id_seq1. The command runs with
              --skip-name-clashes.
        Expected: The output lists the skipped rename. el_chapo keeps gizmo_id_seq1 but is otherwise aligned, and
                  pablo_escobar is aligned.
        """
        self._set_up_an_identity_sequence_name_clash()

        output = self.call_command(skip_name_clashes=True)

        self.assertIn(
            'Renames skipped in default|el_chapo because the name is already in use:\n'
            '    el_chapo.gizmo_id_seq already exists, so gizmo_id_seq1 cannot be renamed to it\n',
            output,
        )
        cursor = connection.cursor()
        cursor.execute("SELECT pg_get_serial_sequence('el_chapo.gizmo', 'id')")
        self.assertEqual(cursor.fetchone()[0], 'el_chapo.gizmo_id_seq1')
        for schema_name in ('el_chapo', 'pablo_escobar'):
            with self.subTest(schema=schema_name):
                self.assertEqual(self._aligned_properties(schema_name), self._aligned_properties('template'))

    def test_rename_to_a_name_already_used_by_another_constraint(self):
        """
        Case: el_chapo's gadget has a primary key named after the table, and a CHECK constraint with the name that the
              template gives that primary key.
        Expected: A CommandError that lists the name already in use, and el_chapo is unchanged.
        """
        self._make_shard_differ_from_template('el_chapo')
        connection.cursor().execute('ALTER TABLE el_chapo.gadget ADD CONSTRAINT legacy_gadget_pkey CHECK (code > 0)')
        properties_before = self._aligned_properties('el_chapo')

        with self.assertRaisesMessage(
            CommandError, 'el_chapo.legacy_gadget_pkey already exists, so gadget_pkey cannot be renamed to it'
        ):
            self.call_command()

        self.assertEqual(self._aligned_properties('el_chapo'), properties_before)

    def test_dry_run_with_skip_name_clashes(self):
        """
        Case: The template's gizmo has the identity sequence gizmo_id_seq. On el_chapo, a sequence that no column owns
              has that name, so el_chapo's gizmo has the identity sequence gizmo_id_seq1. The command runs with
              --dry-run and --skip-name-clashes.
        Expected: The output lists the skipped rename, and el_chapo is unchanged.
        """
        self._set_up_an_identity_sequence_name_clash()
        properties_before = self._aligned_properties('el_chapo')

        output = self.call_command(dry_run=True, skip_name_clashes=True)

        self.assertIn('    el_chapo.gizmo_id_seq already exists, so gizmo_id_seq1 cannot be renamed to it\n', output)
        self.assertEqual(self._aligned_properties('el_chapo'), properties_before)

    def test_leaves_a_serial_column_that_owns_the_sequence_its_default_uses(self):
        """
        Case: On el_chapo, a sequence that no column owns has the name of the template's serial sequence
              gizmo_code_seq. el_chapo's gizmo.code owns gizmo_code_seq1 and takes its values from it.
        Expected: The command does not change the sequence that no column owns, and the column still owns
                  gizmo_code_seq1 and takes its values from it.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE TABLE template.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE TABLE pablo_escobar.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE SEQUENCE el_chapo.gizmo_code_seq')
        cursor.execute('CREATE TABLE el_chapo.gizmo (code SERIAL PRIMARY KEY)')

        output = self.call_command()

        self.assertNotIn('OWNED BY', output)
        cursor.execute("SELECT pg_get_serial_sequence('el_chapo.gizmo', 'code')")
        self.assertEqual(cursor.fetchone()[0], 'el_chapo.gizmo_code_seq1')

    def test_leaves_a_serial_column_owning_one_sequence(self):
        """
        Case: el_chapo's gizmo.code owns gizmo_code_seq, but its default takes its values from ticket_number.
        Expected: The command makes no other sequence owned by the column, which still owns only gizmo_code_seq.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE TABLE template.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE TABLE pablo_escobar.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE TABLE el_chapo.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute("ALTER TABLE el_chapo.gizmo ALTER COLUMN code SET DEFAULT nextval('el_chapo.ticket_number')")

        output = self.call_command()

        self.assertNotIn('OWNED BY', output)
        self.assertNotIn('SET DEFAULT', output)
        cursor.execute("SELECT pg_get_serial_sequence('el_chapo.gizmo', 'code')")
        self.assertEqual(cursor.fetchone()[0], 'el_chapo.gizmo_code_seq')

    def test_leaves_a_sequence_owned_by_another_column_with_the_templates_serial_sequence_name(self):
        """
        Case: On el_chapo, the sequence with the name of the template's serial sequence gizmo_code_seq is owned by
              widget.code. el_chapo's gizmo.code owns no sequence and has no default.
        Expected: The command makes no sequence owned by gizmo.code, and widget.code still owns gizmo_code_seq.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE TABLE template.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE TABLE pablo_escobar.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE TABLE el_chapo.gizmo (code INTEGER PRIMARY KEY)')
        cursor.execute('CREATE SEQUENCE el_chapo.gizmo_code_seq OWNED BY el_chapo.widget.code')

        output = self.call_command()

        self.assertNotIn('OWNED BY', output)
        cursor.execute("SELECT pg_get_serial_sequence('el_chapo.gizmo', 'code')")
        self.assertIsNone(cursor.fetchone()[0])
        cursor.execute(
            'SELECT dep.refobjid::regclass::text, att.attname::text FROM pg_catalog.pg_depend dep'
            ' JOIN pg_catalog.pg_attribute att ON att.attrelid = dep.refobjid AND att.attnum = dep.refobjsubid'
            " WHERE dep.classid = 'pg_catalog.pg_class'::regclass AND dep.objid = 'el_chapo.gizmo_code_seq'::regclass"
            " AND dep.deptype = 'a'"
        )
        self.assertEqual(cursor.fetchall(), [('el_chapo.widget', 'code')])

    @staticmethod
    def _point_widget_default_at_the_templates_sequence(schema_name):
        """Make the shard's widget.code take its values from the template's sequence, and not own the shard's own."""
        cursor = connection.cursor()
        cursor.execute('ALTER SEQUENCE {}.legacy_widget_code_seq OWNED BY NONE'.format(schema_name))
        cursor.execute(
            "ALTER TABLE {}.widget ALTER COLUMN code SET DEFAULT nextval('template.legacy_widget_code_seq')".format(
                schema_name
            )
        )

    @staticmethod
    def _default_of_widget_code(schema_name):
        cursor = connection.cursor()
        cursor.execute(
            'SELECT pg_get_expr(def.adbin, def.adrelid) FROM pg_catalog.pg_attrdef def'
            ' JOIN pg_catalog.pg_attribute att ON att.attrelid = def.adrelid AND att.attnum = def.adnum'
            " WHERE def.adrelid = %s::regclass AND att.attname = 'code'",
            ['{}.widget'.format(schema_name)],
        )
        return cursor.fetchone()[0]

    def test_points_a_serial_default_that_uses_the_templates_sequence_at_the_shards_sequence(self):
        """
        Case: el_chapo's serial column widget.code takes its values from the template's sequence, and two rows were
              inserted that way.
        Expected: After the command, the column takes its values from el_chapo's own sequence, which continues after
                  the two rows, and the template's sequence is unchanged.
        """
        self._point_widget_default_at_the_templates_sequence('el_chapo')
        cursor = connection.cursor()
        cursor.execute('INSERT INTO el_chapo.widget SELECT FROM generate_series(1, 2)')

        self.call_command()

        self.assertEqual(
            self._default_of_widget_code('el_chapo'), "nextval('el_chapo.legacy_widget_code_seq'::regclass)"
        )
        cursor.execute('INSERT INTO el_chapo.widget DEFAULT VALUES RETURNING code')
        self.assertEqual(cursor.fetchone()[0], 3)
        cursor.execute('SELECT last_value, is_called FROM template.legacy_widget_code_seq')
        self.assertEqual(cursor.fetchone(), (2, True))

    def test_pointing_a_serial_default_at_the_shards_sequence_keeps_its_position_when_ahead(self):
        """
        Case: el_chapo's serial column widget.code takes its values from the template's sequence, and el_chapo's own
              sequence for that column was moved past the template's sequence.
        Expected: After the command, the column takes its values from el_chapo's own sequence, which continues from its
                  own position.
        """
        self._point_widget_default_at_the_templates_sequence('el_chapo')
        cursor = connection.cursor()
        cursor.execute('INSERT INTO el_chapo.widget SELECT FROM generate_series(1, 2)')
        cursor.execute("SELECT setval('el_chapo.legacy_widget_code_seq', 50)")

        self.call_command()

        cursor.execute('INSERT INTO el_chapo.widget DEFAULT VALUES RETURNING code')
        self.assertEqual(cursor.fetchone()[0], 51)

    def test_pointing_a_serial_default_at_the_shards_sequence_gives_it_the_templates_bounds_first(self):
        """
        Case: The template's serial sequence counts down below zero, and el_chapo's serial column widget.code takes its
              values from it. el_chapo's own sequence for that column has the default settings, whose bounds exclude
              the template sequence's position, and was never used.
        Expected: After the command, the column takes its values from el_chapo's own sequence, which has the template's
                  settings and continues below the template sequence's position.
        """
        cursor = connection.cursor()
        cursor.execute(
            'ALTER SEQUENCE template.legacy_widget_code_seq INCREMENT BY -1 MINVALUE -1000 MAXVALUE -1 START WITH -1'
            ' RESTART'
        )
        self._point_widget_default_at_the_templates_sequence('el_chapo')
        cursor.execute('ALTER SEQUENCE el_chapo.legacy_widget_code_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647')
        cursor.execute('INSERT INTO el_chapo.widget SELECT FROM generate_series(1, 2)')

        self.call_command(schema_name='el_chapo')

        self.assertEqual(
            self._default_of_widget_code('el_chapo'), "nextval('el_chapo.legacy_widget_code_seq'::regclass)"
        )
        cursor.execute('INSERT INTO el_chapo.widget DEFAULT VALUES RETURNING code')
        self.assertEqual(cursor.fetchone()[0], -3)

    def test_dry_run_prints_the_statements_that_change_a_serial_default(self):
        """
        Case: el_chapo's serial column widget.code takes its values from the template's sequence, and the command runs
              with --dry-run.
        Expected: The output lists the statements that move el_chapo's sequence and change the default, and the column
                  still takes its values from the template's sequence.
        """
        self._point_widget_default_at_the_templates_sequence('el_chapo')

        output = self.call_command(dry_run=True)

        self.assertIn("SELECT setval('el_chapo.legacy_widget_code_seq'::regclass", output)
        self.assertIn(
            '    ALTER TABLE el_chapo.widget ALTER COLUMN code'
            " SET DEFAULT nextval('el_chapo.legacy_widget_code_seq'::regclass);\n",
            output,
        )
        self.assertEqual(
            self._default_of_widget_code('el_chapo'), "nextval('template.legacy_widget_code_seq'::regclass)"
        )

    def test_a_second_run_finds_no_serial_default_to_change(self):
        """
        Case: The command changed a serial default that used the template's sequence, and then runs again.
        Expected: The second run reports that every shard matches the template.
        """
        self._point_widget_default_at_the_templates_sequence('el_chapo')
        self.call_command()

        output = self.call_command()

        self.assertEqual(
            output,
            'default|el_chapo matches the template.\ndefault|pablo_escobar matches the template.\n'
            "Node 'other' has no shards.\n",
        )

    def test_leaves_a_default_that_does_more_than_call_nextval_on_the_templates_sequence(self):
        """
        Case: el_chapo's serial column widget.code owns no sequence, and its default adds 1000 to a value from the
              template's sequence.
        Expected: The command makes el_chapo's sequence owned by the column, but does not change the default or
                  el_chapo's sequence, so the next row still gets the template sequence's value plus 1000.
        """
        self._point_widget_default_at_the_templates_sequence('el_chapo')
        cursor = connection.cursor()
        cursor.execute(
            "ALTER TABLE el_chapo.widget ALTER COLUMN code SET DEFAULT nextval('template.legacy_widget_code_seq') + 1000"
        )
        cursor.execute("SELECT setval('template.legacy_widget_code_seq', 7)")

        output = self.call_command()

        self.assertNotIn('SET DEFAULT', output)
        self.assertEqual(
            self._default_of_widget_code('el_chapo'), "(nextval('template.legacy_widget_code_seq'::regclass) + 1000)"
        )
        cursor.execute('SELECT last_value, is_called FROM el_chapo.legacy_widget_code_seq')
        self.assertEqual(cursor.fetchone(), (1, False))
        cursor.execute('INSERT INTO el_chapo.widget DEFAULT VALUES RETURNING code')
        self.assertEqual(cursor.fetchone()[0], 1008)

    def test_leaves_a_serial_default_that_uses_the_same_sequence_as_the_templates_column(self):
        """
        Case: The template's serial column widget.code and both shards' copies of it take their values from
              shared.code_number, a sequence in another schema, while each column owns its own sequence.
        Expected: The command does not change any default, and reports that every shard matches the template.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE SCHEMA shared')
        cursor.execute('CREATE SEQUENCE shared.code_number')
        for schema_name in ('template', 'el_chapo', 'pablo_escobar'):
            cursor.execute(
                "ALTER TABLE {}.widget ALTER COLUMN code SET DEFAULT nextval('shared.code_number')".format(schema_name)
            )

        output = self.call_command()

        self.assertEqual(
            output,
            'default|el_chapo matches the template.\ndefault|pablo_escobar matches the template.\n'
            "Node 'other' has no shards.\n",
        )
        self.assertEqual(self._default_of_widget_code('el_chapo'), "nextval('shared.code_number'::regclass)")

    def test_does_not_make_a_standalone_sequence_owned_by_a_serial_column_that_uses_it(self):
        """
        Case: el_chapo's gizmo.code owns no sequence and takes its values from ticket_number, which is a standalone
              sequence with non-default settings in the template.
        Expected: The command makes no sequence owned by the column, ticket_number keeps the template's settings for
                  it, and a second run finds nothing to align.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE TABLE template.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute('CREATE TABLE pablo_escobar.gizmo (code SERIAL PRIMARY KEY)')
        cursor.execute(
            "CREATE TABLE el_chapo.gizmo (code INTEGER DEFAULT nextval('el_chapo.ticket_number') PRIMARY KEY)"
        )

        output = self.call_command()

        self.assertNotIn('OWNED BY', output)
        cursor.execute("SELECT pg_get_serial_sequence('el_chapo.gizmo', 'code')")
        self.assertIsNone(cursor.fetchone()[0])
        self.assertEqual(
            self._aligned_properties('el_chapo')['ticket_number_settings'],
            self._aligned_properties('template')['ticket_number_settings'],
        )
        self.assertEqual(
            self.call_command(),
            'default|el_chapo matches the template.\ndefault|pablo_escobar matches the template.\n'
            "Node 'other' has no shards.\n",
        )

    def test_leaves_an_identity_sequence_with_the_name_of_a_standalone_sequence_unchanged(self):
        """
        Case: The template has a standalone sequence gizmo_id_seq with non-default settings, and on el_chapo,
              gizmo_id_seq is the identity sequence of a table.
        Expected: The identity sequence keeps its settings.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE SEQUENCE template.gizmo_id_seq AS integer MAXVALUE 1000')
        cursor.execute('CREATE TABLE el_chapo.gizmo (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)')

        self.call_command()

        cursor.execute(
            'SELECT seqtypid::regtype::text, seqmax FROM pg_catalog.pg_sequence'
            " WHERE seqrelid = 'el_chapo.gizmo_id_seq'::regclass"
        )
        self.assertEqual(cursor.fetchone(), ('bigint', 9223372036854775807))

    def test_leaves_a_serial_columns_sequence_with_the_name_of_a_standalone_sequence_unchanged(self):
        """
        Case: The template has a standalone sequence gizmo_id_seq with a bound of 1000, and on el_chapo, gizmo_id_seq is
              the sequence owned by a serial column of a table.
        Expected: The serial column's sequence keeps its settings.
        """
        cursor = connection.cursor()
        cursor.execute('CREATE SEQUENCE template.gizmo_id_seq AS integer MAXVALUE 1000')
        cursor.execute('CREATE TABLE el_chapo.gizmo (id SERIAL PRIMARY KEY)')

        self.call_command()

        cursor.execute("SELECT seqmax FROM pg_catalog.pg_sequence WHERE seqrelid = 'el_chapo.gizmo_id_seq'::regclass")
        self.assertEqual(cursor.fetchone()[0], 2147483647)
