#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# DjanQuiltDB documentation build configuration file, created by
# sphinx-quickstart on Thu May 25 18:46:41 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import datetime
import os
import sys

sys.path.insert(0, os.path.abspath('../packages/djanquiltdb/src/'))
sys.path.insert(0, os.path.abspath('../packages/djanquiltdb-plugin-postgres-objects/src/'))
import django
from django.conf import settings

from djanquiltdb import __version__
from djanquiltdb_plugin_postgres_objects import __version__ as postgres_objects_version

# The API reference autodocs modules that define models, which needs a populated app registry, not just configured
# settings. The values are the smallest set that satisfies the checks DjanQuiltDBConfig.ready() makes; nothing here
# connects to a database.
settings.configure(
    INSTALLED_APPS=['django.contrib.contenttypes', 'django.contrib.auth', 'djanquiltdb'],
    DATABASES={},
    DATABASE_ROUTERS=['djanquiltdb.router.DynamicDbRouter'],
    QUILT_DB={'SHARD_CLASS': 'djanquiltdb.models.BaseShard'},
)
django.setup()


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    'sphinx.ext.githubpages',
    'sphinx_rtd_theme',
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'djanquiltdb'
copyright = '{} DjanQuiltDB Project, 2023-2025, Cloud Linux Software, Inc.; 2017-2023, Patchman B.V.'.format(
    datetime.date.today().year
)
author = 'DjanQuiltDB Project; Cloud Linux Software, Inc.; Patchman B.V.'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#

release = version = __version__

# One substitution per plugin, so each plugin's pages can state their own release.
rst_epilog = """
.. |postgres-objects-version| replace:: {}
""".format(postgres_objects_version)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# The header the sidebar and the narrow-screen bar share, in the dark green the social preview card uses.
html_theme_options = {'style_nav_header_background': '#092e20'}

# docs/_templates/layout.html restyles that header; without this it is not picked up at all.
templates_path = ['_templates']

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The favicon is a variant of the logo drawn for small sizes: the full icon's stitching blurs into a smudge below about
# 32 pixels.
html_logo = '../assets/icon.svg'
html_favicon = '../assets/icon-32.png'

# Only to style the sidebar header the template above replaces; see the file itself.
html_css_files = ['custom.css']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = project


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        '.tex',
        '{} Documentation'.format(project),
        'DjanQuiltDB Project; Cloud Linux Software, Inc.; Patchman B.V.',
        'manual',
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'djanquiltdb', '{} Documentation'.format(project), [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        project,
        '{} Documentation'.format(project),
        author,
        project,
        'One line description of project.',
        'Miscellaneous',
    ),
]
